name: unscientific
author: Franklin Chen
maintainer: franklinchen@franklinchen.com
extra-source-files:
- README.md
ghc-options: -Wall -O2 -rtsopts
dependencies:
- base >=4 && <=5
- primitive
- mwc-random
executables:
  unscientific:
    main: Main.hs
    source-dirs: src
